# Generated by Django 4.2.5 on 2024-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0002_alter_risk_risk_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
