# Generated by Django 4.2.5 on 2024-10-21 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk_manager', '0003_alter_risk_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='date_closed',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='date_opened',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
