# Generated by Django 4.2.5 on 2024-12-08 10:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk_manager', '0004_risk_date_closed_risk_date_opened_risk_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikely'), (2, '2 - Possible'), (3, '3 - Likely'), (4, '4 - Certain')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Unlikely'), (2, '2 - Possible'), (3, '3 - Likely'), (4, '4 - Certain')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='RiskUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_manager.risk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='updators',
            field=models.ManyToManyField(related_name='updated_risks', through='risk_manager.RiskUpdate', to=settings.AUTH_USER_MODEL),
        ),
    ]
