# Generated by Django 4.2.5 on 2024-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_risk_deadlines', models.BooleanField(blank=True, default=True)),
                ('allow_changable_date_reported', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'GlobalSetting',
                'verbose_name_plural': 'GlobalSettings',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='is_super_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
