# Generated by Django 4.2.5 on 2024-10-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_super_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
