# Generated by Django 4.2.5 on 2024-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
