# Generated by Django 4.2.5 on 2024-11-22 00:54

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uploaded_profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=apps.authentication.models.profile_pic_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='[avatars/(7).jpg]', max_length=255),
        ),
    ]
