# Generated by Django 4.2.5 on 2024-12-08 10:38

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_uploaded_profile_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uploaded_profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=apps.authentication.models.profile_pic_upload_path, validators=[apps.authentication.models.validate_file_size]),
        ),
    ]
